-- Insert statements for the CollectionItemDetails table
INSERT INTO CollectionItemDetails (
    CandyMachineAndCollectionId,
    collectionurl,
    collectionSubtitles,
    collectionDetails,
    collectionCandibarValue,
    collectionStatus,
    isSwappable,
    zodiacSign,
    zodiacYear,
    zodiacIcon,
    Images
) 
VALUES 
(
    1, 
    '', 
    'Snake NFT Collection 2025', 
    'The Snake NFT Collection 2025 is a unique digital art collection that celebrates the spirit of the Snake zodiac sign. Each NFT in this collection represents the values and culture of the Snake community. The collection features a variety of styles and themes, all centered around the concept of the Snake. By owning a Snake NFT, you become part of a vibrant community of collectors and enthusiasts who share a passion for digital art and the Snake lifestyle.', 
    600, 
    'AVAILABLE', 
    false, 
    'wood snake', 
    '2025', 
    '', 
    '[{"name": "Snake NFT Collection 2025 #1", "url": "/api/image/CandibarImg/Woodsnake/snake0_2025_500-bJMtUmup4TT8xdikHCLhEcf2a4QiBj.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    2,
    '', 
    'Snake NFT Collection 2025', 
    'The Snake NFT Collection 2025 is a unique digital art collection that celebrates the spirit of the Snake zodiac sign. Each NFT in this collection represents the values and culture of the Snake community. The collection features a variety of styles and themes, all centered around the concept of the Snake. By owning a Snake NFT, you become part of a vibrant community of collectors and enthusiasts who share a passion for digital art and the Snake lifestyle.', 
    950, 
    'AVAILABLE', 
    false, 
    'wood snake', 
    '2025', 
    '', 
    '[{"name": "Snake NFT Collection 2025 #2", "url": "/api/image/CandibarImg/Woodsnake/snake1_2025_500-MGjeQCWhDX4auQ7ioZ6a4rN6x6QaMU.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    3,
    '', 
    'Snake NFT Collection 2025', 
    'The Snake NFT Collection 2025 is a unique digital art collection that celebrates the spirit of the Snake zodiac sign. Each NFT in this collection represents the values and culture of the Snake community. The collection features a variety of styles and themes, all centered around the concept of the Snake. By owning a Snake NFT, you become part of a vibrant community of collectors and enthusiasts who share a passion for digital art and the Snake lifestyle.', 
    1500, 
    'AVAILABLE', 
    false, 
    'wood snake', 
    '2025', 
    '', 
    '[{"name": "Snake NFT Collection 2025 #3", "url": "/api/image/CandibarImg/Woodsnake/snake2_2025_500-cuGv4oWV1r1L9O1BKd5sU6lDOu8SDJ.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    4,
    '', 
    'Snake NFT Collection 2025', 
    'The Snake NFT Collection 2025 is a unique digital art collection that celebrates the spirit of the Snake zodiac sign. Each NFT in this collection represents the values and culture of the Snake community. The collection features a variety of styles and themes, all centered around the concept of the Snake. By owning a Snake NFT, you become part of a vibrant community of collectors and enthusiasts who share a passion for digital art and the Snake lifestyle.', 
    2025, 
    'AVAILABLE', 
    false, 
    'wood snake', 
    '2025', 
    '', 
    '[{"name": "Snake NFT Collection 2025 #4", "url": "/api/image/CandibarImg/Woodsnake/snake3_2025_500-KgeF1pu8XxUEtF4PKIk2MCwl4jyPRw.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    5,
    '', 
    'Candi NFT Collection', 
    'The Candi NFT Collection is a unique digital art collection that celebrates the spirit of the Candi community. Each NFT in this collection represents the values and culture of the Candi community. The collection features a variety of styles and themes, all centered around the concept of Candi. By owning a Candi NFT, you become part of a vibrant community of collectors and enthusiasts who share a passion for digital art and the Candi lifestyle.', 
    500, 
    'AVAILABLE', 
    true, 
    '', 
    '', 
    '', 
    '[{"name": "Candi NFT 2025 #1", "url": "/api/image/CandibarImg/Candi/candi_00_500-2WxvpIIqCmHZBtBjBZTNYPzf8RRrCP.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Candi NFT 2025 #2", "url": "/api/image/CandibarImg/Candi/candi_01_500-y4ReaS9fjPQCDGtPEK2ELI5oJ5LTPy.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Candi NFT 2025 #3", "url": "/api/image/CandibarImg/Candi/candi_02_500-BcGaCj5UpkRskrh4gsbp7Ihcx1WgJ1.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Candi NFT 2025 #4", "url": "/api/image/CandibarImg/Candi/candi_03_500-WTiNFp0A2zWdz3mx5eXCAMa0YNwIAE.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    6,
    '', 
    'Capricorn Dates: December 21-January 20', 
    'Capricorn Dates: December 21-January 20. Capricorn is an earth sign, ruled by Saturn, and is known for its practicality, discipline, and ambition.', 
    600, 
    'AVAILABLE', 
    false, 
    'Capricorn', 
    '', 
    '/zodiacSignsImg/Capricorn.png', 
    '[{"name": "Capricorn NFT #1", "url": "/api/image/CandibarImg/Zodiac/Capricorn/CapricornC1-EHWUsHNP45fc5uJUaLYeDTQ8C1sCXc.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Capricorn NFT #2", "url": "/api/image/CandibarImg/Zodiac/Capricorn/CapricornC2-Ij1KNY0k58CfSqJHm4X7ItOJn35hwu.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Capricorn NFT #3", "url": "/api/image/CandibarImg/Zodiac/Capricorn/CapricornC3-n9Gw8tippbHY7IBiSiV0HzWLHoiFeY.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Capricorn NFT #4", "url": "/api/image/CandibarImg/Zodiac/Capricorn/CapricornC4-YUrbJQD94CVZAZyrHISoL2sIn51Rts.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    7,
    '', 
    'Aquarius Dates: January 21-February 18', 
    'Aquarius Dates: January 21-February 18. Aquarius is an air sign, ruled by Uranus, and is known for its innovation, independence, and humanitarianism.', 
    600, 
    'AVAILABLE', 
    false, 
    'Aquarius', 
    '', 
    '/zodiacSignsImg/Aquarius.png', 
    '[{"name": "Aquarius NFT #1", "url": "/api/image/CandibarImg/Zodiac/Aquarius/AquariusC1-K2fHJ70RX6SXU4nRKHBEdqnutdeb8I.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Aquarius NFT #2", "url": "/api/image/CandibarImg/Zodiac/Aquarius/AquariusC2-wU1QlxiEDbQCHgD6Pzj0vmqabPIdLA.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Aquarius NFT #3", "url": "/api/image/CandibarImg/Zodiac/Aquarius/AquariusC3-EZzHH9yhPOIXKNW9mSgWMIygjAOLp2.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Aquarius NFT #4", "url": "/api/image/CandibarImg/Zodiac/Aquarius/AquariusC4-TzZ0ZGRGDlGqnQbMCPF58xyn8WLvUF.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    8,
    '', 
    'Pisces Dates: February 19-March 20', 
    'Pisces Dates: February 19-March 20. Pisces is a water sign, ruled by Neptune, and is known for its empathy, intuition, and artistic nature.', 
    600, 
    'AVAILABLE', 
    false, 
    'Pisces', 
    '', 
    '/zodiacSignsImg/Pisces.png', 
    '[{"name": "Pisces NFT #1", "url": "/api/image/CandibarImg/Zodiac/Pisces/PiscesC1-3oSkfYloXHbN0Qqt49ltWe1zzFF6zW.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Pisces NFT #2", "url": "/api/image/CandibarImg/Zodiac/Pisces/PiscesC2-cFZNTHQew6TOePQO4kSijnoLzuOmxu.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Pisces NFT #3", "url": "/api/image/CandibarImg/Zodiac/Pisces/PiscesC3-rv5SAuDnMjcM0CvYu4d6NGnu7KDm1I.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Pisces NFT #4", "url": "/api/image/CandibarImg/Zodiac/Pisces/PiscesC4-5QRma2mpOnXgDkOBANmZNg5vZHrx5n.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    9,
    '', 
    'Aries Dates: March 21-April 19', 
    'Aries Dates: March 21-April 19. Aries is a fire sign, ruled by Mars, and is known for its courage, determination, and enthusiasm.', 
    600, 
    'AVAILABLE', 
    false, 
    'Aries', 
    '', 
    '/zodiacSignsImg/Aries.png', 
    '[{"name": "Aries NFT #1", "url": "/api/image/CandibarImg/Zodiac/Aries/AriesC1-HIAtbgnp56MKdtr79CBmgb5n9ZBpb9.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Aries NFT #2", "url": "/api/image/CandibarImg/Zodiac/Aries/AriesC2-acZgmSyz4asyhbuEyuRvWV6XRhZMW0.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Aries NFT #3", "url": "/api/image/CandibarImg/Zodiac/Aries/AriesC3-WlzGBpmwKAXYqj0r4IiGdSIsgDKNU1.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Aries NFT #4", "url": "/api/image/CandibarImg/Zodiac/Aries/AriesC4-ujJsWrOBazGg0DmRRigMBiesMnDExx.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
);



-- Insert statements for the CollectionItemDetails table
INSERT INTO CollectionItemDetails (
    CandyMachineAndCollectionId,
    collectionurl,
    collectionSubtitles,
    collectionDetails,
    collectionCandibarValue,
    collectionStatus,
    isSwappable,
    zodiacSign,
    zodiacYear,
    zodiacIcon,
    Images
) 
VALUES 
(
    10,
    '', 
    'Taurus Dates: April 20-May 20', 
    'Taurus Dates: April 20-May 20. Taurus is an earth sign, ruled by Venus, and is known for its practicality, reliability, and sensuality.', 
    600, 
    'AVAILABLE', 
    false, 
    'Taurus', 
    '', 
    '/zodiacSignsImg/Taurus.png', 
    '[{"name": "Taurus NFT #1", "url": "/api/image/CandibarImg/Zodiac/Taurus/TaurusC1-Y8SSQdh0Jek9ylKyPzvNLfgCBXa6Xw.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Taurus NFT #2", "url": "/api/image/CandibarImg/Zodiac/Taurus/TaurusC2-h3NcjJeTujjUDWk4VmbBvsrU1zTdnK.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Taurus NFT #3", "url": "/api/image/CandibarImg/Zodiac/Taurus/TaurusC3-5dbuemSVRpvAvMdEUHjbBxI2yGt72Q.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Taurus NFT #4", "url": "/api/image/CandibarImg/Zodiac/Taurus/TaurusC4-EVeXUbgC64p1ZRf7YWzBHjz6Sw8xdf.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    11,
    '', 
    'Gemini Dates: May 21-June 20', 
    'Gemini Dates: May 21-June 20. Gemini is an air sign, ruled by Mercury, and is known for its adaptability, curiosity, and sociability.', 
    600, 
    'AVAILABLE', 
    false, 
    'Gemini', 
    '', 
    '/zodiacSignsImg/Gemini.png', 
    '[{"name": "Gemini NFT #1", "url": "/api/image/CandibarImg/Zodiac/Gemini/GeminiC1-rfIp8eYcNrCoqz3kVpyjiXWVAiqyvf.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Gemini NFT #2", "url": "/api/image/CandibarImg/Zodiac/Gemini/GeminiC2-I8gI0kcaEtgTnoSPQt167zjCZasWXI.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Gemini NFT #3", "url": "/api/image/CandibarImg/Zodiac/Gemini/GeminiC3-p3NK6kHGXPQAMPcYAYjk3T3as9zVwV.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Gemini NFT #4", "url": "/api/image/CandibarImg/Zodiac/Gemini/GeminiC4-s6QrHgF44Vp2obvhPckLc3EqETVksa.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    12,
    '', 
    'Cancer Dates: June 21-July 22', 
    'Cancer Dates: June 21-July 22. Cancer is a water sign, ruled by the Moon, and is known for its emotional depth, intuition, and nurturing nature.', 
    600, 
    'AVAILABLE', 
    false, 
    'Cancer', 
    '', 
    '/zodiacSignsImg/Cancer.png', 
    '[{"name": "Cancer NFT #1", "url": "/api/image/CandibarImg/Zodiac/Cancer/CancerC1-S8uqYZEYbDwkYKRq5dxWL5SSewHioH.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Cancer NFT #2", "url": "/api/image/CandibarImg/Zodiac/Cancer/CancerC2-ivVQktPfWFWIjA96uqhoMc9F1xQ6SU.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Cancer NFT #3", "url": "/api/image/CandibarImg/Zodiac/Cancer/CancerC3-HD94YLcanqeuFoxUdh18hTXeBilMzj.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Cancer NFT #4", "url": "/api/image/CandibarImg/Zodiac/Cancer/CancerC4-ydFUjAVXooVbmoW3z16gwkSPN5J1zn.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    13,
    '', 
    'Dates: July 23-August 22',
    'Leo Dates: July 23-August 22. Leo is a fire sign, ruled by the Sun, and is known for its confidence, creativity, and generosity.',
    600, 
    'AVAILABLE', 
    false, 
    'Leo', 
    '', 
    '/zodiacSignsImg/Leo.png', 
    '[{"name": "Leo NFT #1", "url": "/api/image/CandibarImg/Zodiac/Leo/LeoC1-g1zB19IEyDlUHScvWZ6yMxW210zoIz.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Leo NFT #2", "url": "/api/image/CandibarImg/Zodiac/Leo/LeoC2-nlXA3KUdsPffagEIGGJcROYaya5EmP.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Leo NFT #3", "url": "/api/image/CandibarImg/Zodiac/Leo/LeoC3-qHuGNfGHS7uAHb9l62PQMwWOWl0uQh.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Leo NFT #4", "url": "/api/image/CandibarImg/Zodiac/Leo/LeoC4-7tTNgsqQRmYjc8FEgunlSjLhO1zWNy.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    14,
    '', 
    'Dates: August 23-September 22',
    'Virgo Dates: August 23-September 22. Virgo is an earth sign, ruled by Mercury, and is known for its attention to detail, practicality, and analytical nature.',
    600, 
    'AVAILABLE', 
    false, 
    'Virgo', 
    '', 
    '/zodiacSignsImg/Virgo.png', 
    '[{"name": "Virgo NFT #1", "url": "/api/image/CandibarImg/Zodiac/Virgo/VirgoC1-WgMM8uEHbNLBNRH2RS4EQdxk4Hwfcb.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Virgo NFT #2", "url": "/api/image/CandibarImg/Zodiac/Virgo/VirgoC2-t2FnayQe4hgio19V1uIqRxWWugpmQN.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Virgo NFT #3", "url": "/api/image/CandibarImg/Zodiac/Virgo/VirgoC3-35LsaMvfLSOEI75uhYfMVYmUk22CpC.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Virgo NFT #4", "url": "/api/image/CandibarImg/Zodiac/Virgo/VirgoC4-4KRIqAyZMVzvlDCZK4JulapDFfDI9Z.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Virgo NFT #5", "url": "/api/image/CandibarImg/Zodiac/Virgo/VirgoC6-mwHs5B2UBQ2bT7lg5Ml5SgjecsEGEd.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    15,
    '', 
    'Dates: September 23-October 22',
    'Libra Dates: September 23-October 22. Libra is an air sign, ruled by Venus, and is known for its diplomacy, charm, and sense of justice.',
    600, 
    'AVAILABLE', 
    false, 
    'Libra', 
    '', 
    '/zodiacSignsImg/Libra.png', 
    '[{"name": "Libra NFT #1", "url": "/api/image/CandibarImg/Zodiac/Libra/LibraC1-KAgIiEkrIXnOhlFo0xGCS8W0uE77bU.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Libra NFT #2", "url": "/api/image/CandibarImg/Zodiac/Libra/LibraC2-MLeuJGMAltKjaDw70ioMCOMuOgxXm2.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Libra NFT #3", "url": "/api/image/CandibarImg/Zodiac/Libra/LibraC3-q0cWAKp6oSdsalsLcJ6kSSwwENjf1t.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Libra NFT #4", "url": "/api/image/CandibarImg/Zodiac/Libra/LibraC4-pPCGMhg7OAjo3yCCexi9z6OrJBfSOh.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    16,
    '', 
    'Dates: October 23-November 21',
    'Scorpio Dates: October 23-November 21. Scorpio is a water sign, ruled by Pluto, and is known for its intensity, passion, and resourcefulness.',
    600, 
    'AVAILABLE', 
    false, 
    'Scorpio', 
    '', 
    '/zodiacSignsImg/Scorpio.png', 
    '[{"name": "Scorpio NFT #1", "url": "/api/image/CandibarImg/Zodiac/Scorpio/ScorpioC1-9elBjwZxP03LV61c8oTs5sDZ7v4xT8.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Scorpio NFT #2", "url": "/api/image/CandibarImg/Zodiac/Scorpio/ScorpioC2-snkSD8dalKu4esVN8BLCJkzUHJvWDC.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Scorpio NFT #3", "url": "/api/image/CandibarImg/Zodiac/Scorpio/ScorpioC3-uYQbjjrZZNYDVOyoFLZR3KPGsFb8xB.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Scorpio NFT #4", "url": "/api/image/CandibarImg/Zodiac/Scorpio/ScorpioC4-CsOVMYMOnsjSRnqTc4Lhga6C7O0AS5.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
),
(
    17,
    '', 
    'Dates: November 22-December 21',
    'Sagittarius Dates: November 22-December 21. Sagittarius is a fire sign, ruled by Jupiter, and is known for its adventurous spirit, optimism, and love of freedom.',
    600, 
    'AVAILABLE', 
    false, 
    'Sagittarius', 
    '', 
    '/zodiacSignsImg/Sagittarius.png', 
    '[{"name": "Sagittarius NFT #1", "url": "/api/image/CandibarImg/Zodiac/Sagittarius/SagittariusC1-U87giVQYJLznaVTTScToLv7mBMxQoH.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Sagittarius NFT #2", "url": "/api/image/CandibarImg/Zodiac/Sagittarius/SagittariusC2-QzrAxj804wGnC9VVKdZa576igmhAyN.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Sagittarius NFT #3", "url": "/api/image/CandibarImg/Zodiac/Sagittarius/SagittariusC3-343gAe3pEMJhwtMBE0mXqlKRGLrJC9.jpg", "mimetype": "image/jpeg", "iscover": "0"}, {"name": "Sagittarius NFT #4", "url": "/api/image/CandibarImg/Zodiac/Sagittarius/SagittariusC4-L6J1ca7ROJ6NRUHxIl81F9OsskXucH.jpg", "mimetype": "image/jpeg", "iscover": "0"}]'::JSONB
);