export { GetStartedView } from "./getstarted";
export { HomeView } from "./home";
export { BasicsView } from "./basics";
export { NFTSwapView } from "./nftswap";
export { CandiView } from "./candi";
export { FAQView } from "./faq";
export { EscrowView } from "./escrow";
export {TermsOfServiceView} from "./tos";
export {PrivacyPolicyView} from "./pp";
export {AstrologyZodiacView} from "./astrology/zodiac/index";
export {AstrologySignView} from "./astrology/sign";
export {CPAGView} from "./platformassetguide";
export { FilterAstrologyZodiacView } from "./astrology/zodiac/FilterAstrologyZodiacView";